### ISSUE TITLE
Crash with Warptorio2

### ISSUE THREAD

**Issue by Neb2566** [year6b7a/item-network-factorio-mod#13]
Saw it much later to report issues here, I guess since this is checked more.

Screenshot of error message:
Found a similar issue on Warptorio's page with Factorissimo, and warptorio author says its on Factorissimo's end.

https://imgur.com/a/BIjcKuI

**Comment by year6b7a** [comment]
Fixed with https://github.com/year6b7a/item-network-factorio-mod/commit/75f1bc78511e3c4cc694e581f157ae11d7aa5d49
