### ISSUE TITLE
Suggestion: Game setting

### ISSUE THREAD

**Issue by Neb2566** [year6b7a/item-network-factorio-mod#14]
A suggestion for game setting to decide the automatic buffer when pasting from machine to the chest :)

**Comment by year6b7a** [comment]
Good idea. Implemented in 5f94a323097e38659eb45eae6342e8e58f3b72ff

![image](https://github.com/year6b7a/item-network-factorio-mod/assets/135451123/5a2c6bf1-eaf1-43e5-a167-0fa37edd77eb)
