### ISSUE TITLE
Suggestion: Network Loader filter specifies which resource to put on the separate belt lanes

### ISSUE THREAD

**Issue by schmitzrj** [year6b7a/item-network-factorio-mod#16]
Thanks for a great, time-saving mod! I would like to suggest that the Network Loader filter has two slots, one for each of the two lanes available on a belt. That way we can put two items into a dedicated belt lane and optimize the belt for a line of machines making the same thing with two ingredients on a dedicated belt. It can also help eliminate the issue of overproduction because it won't matter if the belt gets overloaded because of the dedicated lane that will make each resource always be able to flow through.

**Comment by year6b7a** [comment]
I would also like to implement this but I'm not sure how to do it efficiently.

Under the hood, this mod tries to let vanilla factorio do as much of the heavy lifting as possible for UPS. This means network loaders are just vanilla loaders and I don't think there's a way to set per-lane filters to loaders.

I'll mark this one as "help wanted" in case any experienced factorio modders stumble across this thread, or as a reminder to revisit this if per-lane loader filters get added.

In the meantime, this setup works well for me to load both sides of a belt:
![image](https://github.com/year6b7a/item-network-factorio-mod/assets/135451123/291ffeec-021e-4599-a77d-9d2485b62736)

**Comment by year6b7a** [comment]
Closing as won't do for now.
