### ISSUE TITLE
Cannot paste settings on existing chest.

### ISSUE THREAD

**Issue by Neb2566** [year6b7a/item-network-factorio-mod#18]
Noticed I cannot paste blueprinted settings to already existing chest, that would be nice :)

**Comment by year6b7a** [comment]
Looks like this is another gap in the blueprints API. [Relevant forum thread](https://forums.factorio.com/viewtopic.php?f=28&t=103934&p=587462#p587462).

Closing this ticket for now until entity metadata gets fixed.
