### ISSUE TITLE
Suggestion: Circuit Connector

### ISSUE THREAD

**Issue by Nivalux** [year6b7a/item-network-factorio-mod#31]
A nice QoL feature would be either an interface for the circuit network in order to read all the items and fluids stored in the network.

This could either be by adding the circuit network support to the existing chest / tank or probably better by adding a separate item that is just a reading connector for it.

It is not a critical thing that's missing, but it would allow more automation and allow reading and displaying some item stats.

**Comment by Nivalux** [comment]
Having played a bit longer it would be really great if it would be possible to set the request and provide items via circuit connection.
I am playing a Warptorio run with K2 and space is a premium. So I would like to use the Crafting Combinator mod, which would require me to be able to set requests and the produced items via circuit network.
Even when I unlock drones, I would still need to have a point where I put parts of all the items into the logisitc network for it to work.

**Comment by year6b7a** [comment]
Interesting ideas. I've been thinking along similar lines and will probably implement circuit connectivity in the next couple of weeks. I'm curious how flexible the circuit API is and if I can use it over the entire network without adding lag.

**Comment by year6b7a** [comment]
Basic version implemented in `0.8.1`. I'll keep an eye out for early feedback to see what changes need to be made.
