### ISSUE TITLE
Destroyed and rebuilt nodes lose settings

### ISSUE THREAD

**Issue by bengardner** [year6b7a/item-network-factorio-mod#33]
I'm new to factorio, so I'm not sure how it all works internally.
A ghost is created when a node is destroyed. It is then rebuilt via a constructor robot.
Sometimes (always?) rebuilt chest/liquid nodes lose their configuration.
That can be tricky to notice.
Ideally, the settings would be preserved. 
If that isn't possible (if the ghost is created by another mod), perhaps an alert can be raised for unconfigured nodes?

**Comment by year6b7a** [comment]
Fixed in fbe1a7a83d80ee91bacc46fdd81462973d836271.
