### ISSUE TITLE
Make Network View draggable

### ISSUE THREAD

**Issue by year6b7a** [year6b7a/item-network-factorio-mod#53]
Right now, the "Network View" panel isn't draggable. This should definitely be possible since other mods like [Factory Planner](https://github.com/ClaudeMetz/FactoryPlanner) have windows with inline buttons.

**Comment by year6b7a** [comment]
Fixed while working on 5e3a1d8a1ed6a2d752bca00c7f3d4d05cc9d1fa6.

**Comment by bengardner** [comment]
Thanks. I knew I was missing something simple.
