### ISSUE TITLE
enhancement: pull items directly out of the Network View to player inventory or cursor

### ISSUE THREAD

**Issue by bengardner** [year6b7a/item-network-factorio-mod#54]
I find myself building requester chests early game just to pull items out of the item network.
This is before personal logistics are available.

It would be nice to be able to pull items directly from the Network View dialog on the item tab.
Maybe use the same ctrl/shift/left/right click semantics used elsewhere in the game?

**Comment by year6b7a** [comment]
100% agree.

**Comment by bengardner** [comment]
#57 gets this working.
We may need to fine-tune the various click/control/shift combos, but I'm happy with it.
