### ISSUE TITLE
bug: stone-brick vs stone-path crash on shortage page

### ISSUE THREAD

**Issue by bengardner** [year6b7a/item-network-factorio-mod#60]
Put down some stone bricks to create a path. Have no extra stone bricks in the item network or inventory.
CTRL-C to copy the path. Paste. 
View the shortage page. Crash.

The problem is that the "alert" stuff is showing a shortage of "stone-path" and not "stone-brick".
"stone-path" isn't an item, so the lookup fails.

As far as I know, this is a special case.
The other similar case is "concrete", but that has the same name for the tile and item.

Probably ought to translate "stone-path" to "stone-brick".

Another option is to ignore any "shortage" that isn't defined in the item_prototypes.

**Comment by bengardner** [comment]
Fixed by #61

**Comment by year6b7a** [comment]
Nice catch!

**Comment by bengardner** [comment]
Also not handling "item-request-proxy", which is used to request a module for a factory.
I think I should add something for missing repair kits as well.

**Comment by bengardner** [comment]
All fixed.
#62

**Comment by year6b7a** [comment]
Thanks!
